#!/bin/sh

plugin_id=org.dita-ng.doctypes

# The script's parent directory
pushd `dirname $0` > /dev/null
parent_dir=`pwd -P`
popd > /dev/null


# The "dita" command
dita_cmd="$parent_dir/dita"
found=1
if [ ! -e $dita_cmd ]; then
  found=0
elif [ -d $dita_cmd ]; then
  found=0
elif [ ! -x $dita_cmd ]; then
    found=0
fi
if [ $found -ne 1 ]; then
    echo "Did not find the \"dita\" script in $parent_dir" 1>&2
    exit 1
fi

export DITA_DIR=`dirname $parent_dir`

plugin_dir=$DITA_DIR/plugins/$plugin_id

# plugin-dir is here in case dita-ng.properties is present
export CLASSPATH=$plugin_dir
export CLASSPATH=$CLASSPATH:$plugin_dir/lib/dita-ng.jar
export CLASSPATH=$CLASSPATH:$plugin_dir/lib/jing.jar

$dita_cmd $*

